import path from 'path';
import fs from 'fs';
import { exec } from 'child_process';
import { get, merge } from 'lodash';

import { config, IResolvedProjectConfig, CLIError, CLICommand } from '@common';
import { createProjectConfig } from '@project-config';
import logger from '@logger';

import { IProjectOptions } from '../types';

export default class ProjectCreatorController {
  private projectDir: string;
  private projectConfig: IResolvedProjectConfig;
  private options: IProjectOptions;
  private isCurrentDir: boolean;

  constructor(options: IProjectOptions) {
    const workDir = options.cwd || process.cwd();
    const projectName = options.name || path.basename(workDir);

    this.isCurrentDir = !!options.name && options.name === '.';
    this.projectDir = this.isCurrentDir ? workDir : path.join(workDir, projectName);
    this.options = { ...options, name: projectName, cwd: workDir };
    this.projectConfig = createProjectConfig(options.type, {}, this.projectDir);
  }

  public async createProject(): Promise<void> {
    if (!this.isCurrentDir && fs.existsSync(this.projectDir)) {
      throw new CLIError(`Project ${this.options.name} is already exists!`);
    }

    if (this.isCurrentDir && this.isInitialized()) {
      throw new CLIError('Cannot create a project! The directory is not empty!');
    }

    await this.createConfig();
    await this.createDirectories();

    if (!this.options.nonpm) {
      await this.updatePackage();
    }

    if (this.options.git && !this.isGitInitialized()) {
      await this.initGit();
    }

    if (this.isGitInitialized()) {
      await this.updateGitignore();
    }

    if (this.isNpmPackageInitialized()) {
      await this.installDependencies();
    }
  }

  public async updatePackage() {
    logger.info('📦 Initializing npm package...');
    const packagePath = path.join(this.projectDir, 'package.json');

    const packageData = {
      name: this.options.name,
      version: get(this.options, 'version', '0.1.0'),
      author: get(this.options, 'author', config.title),
      description: get(this.options, 'description', `This project was generated by ${config.title} CLI`)
    };

    if (fs.existsSync(packagePath)) {
      merge(
        packageData,
        JSON.parse(
          await fs.promises.readFile(packagePath, 'utf8')
        )
      );
    }

    merge(packageData, {
      scripts: {
        build: `${config.command} ${CLICommand.Build}`,
        watch: `${config.command} ${CLICommand.Build} --watch`,
        postinstall: `${config.command} ${CLICommand.Install}`
      }
    });

    await fs.promises.writeFile(packagePath, JSON.stringify(packageData, null, 2));
  }

  public async createConfig() {
    logger.info('🔧 Creating project configuration file...');

    await fs.promises.mkdir(this.projectDir, { recursive: true });
    const configPath = path.join(this.projectDir, config.project.configFile);

    const projectConfig = merge({}, this.projectConfig.defaults);

    await fs.promises.writeFile(configPath, JSON.stringify(projectConfig, null, 2));
  }

  public async createDirectories() {
    logger.info('📁 Creating project directories...');

    for (const target of this.projectConfig.targets.assets) {
      await fs.promises.mkdir(target.src, { recursive: true });
    }

    for (const target of this.projectConfig.targets.include) {
      await fs.promises.mkdir(target.src, { recursive: true });
    }

    for (const target of this.projectConfig.targets.scripts) {
      await fs.promises.mkdir(target.src, { recursive: true });
    }
  }

  public async installDependencies() {
    logger.info('🔄 Installing dependencies...');
    await this.execCommand(`npm install ${config.command}@${config.version} --save-dev`);
    await this.execCommand('npm run postinstall');
  }

  public async initGit() {
    logger.info('🌿 Initializing git...');
    await this.execCommand('git init');
  }

  public async updateGitignore(): Promise<void> {
    logger.info('❔ Updating .gitignore file...');
    const filePath = path.join(this.projectDir, '.gitignore');

    const lines = [`*.${this.projectConfig.compiler.config.fileExtensions.plugin}`];

    const addDir = (dir: string) => !path.isAbsolute(dir) && lines.push(
      `${path.relative(this.projectDir, dir)}/`
    );

    addDir('node_modules');
    addDir(this.projectConfig.compiler.dir);
    addDir(this.projectConfig.thirdparty.dir);

    for (const target of this.projectConfig.targets.assets) {
      addDir(target.src);
    }

    if (fs.existsSync(filePath)) {
      lines.unshift('');
    }

    lines.push('');

    await fs.promises.appendFile(filePath, lines.join('\n'));
  }

  public isInitialized(): boolean {
    return fs.existsSync(path.join(this.projectDir, config.project.configFile));
  }

  public isGitInitialized(): boolean {
    return fs.existsSync(path.join(this.projectDir, '.git'));
  }

  public isNpmPackageInitialized(): boolean {
    return fs.existsSync(path.join(this.projectDir, 'package.json'));
  }

  public execCommand(command: string) {
    return new Promise(resolve => {
      const process = exec(command, { cwd: this.projectDir });

      process.on('error', resolve);
      process.on('close', resolve);
    });
  }
}
